---
title: "Data Prep"
author: "Brad Anderson"
date: "November 1, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(dismo)
library(tidyverse)
library(sf)
library(sp)
library(rgdal)
library(maptools)
```

```{r}
#Climate Variables Folder
variable_path <- file.path("H:/MaxEnt/Environmental Variables/Climate/Historical/1981-2010")

#Soil
#soils <- raster("H:/SDM/Soils/top_soils.tif")

#DEM
DEM <- raster("H:/MaxEnt/Environmental Variables/Elevation Slope Aspect/DEM.tif")

#Aspect
aspect <- raster("H:/MaxEnt/Environmental Variables/Elevation Slope Aspect/Aspect.tif")

#Slope
slope <- raster("H:/MaxEnt/Environmental Variables/Elevation Slope Aspect/Slope.tif")
```

```{r}
#Call all .tif files from the storage location
variables <- list.files(variable_path, pattern='tif$', full.names=TRUE )

#Stack climate tif files into a RasterStack
climate <- stack(variables)

#Define project (For some reason the BCM data comes unprojected)
crs(climate) <- CRS('+init=epsg:3310')
```

```{r}
#Re-assign numbers
#soils_reclass <- reclassify(soils,rcl=c(120,150,NA))
aspect_reclass <- reclassify(aspect,rcl=c(-Inf,0,NA))
slope_reclass <- reclassify(slope,rcl=c(-Inf,0,NA))

#Reproject to NAD83 CA Teale Albers
#soils_proj <- projectRaster(soils_reclass, crs=crs(climate))
DEM_proj <- projectRaster(DEM, crs=crs(climate))
aspect_proj <- projectRaster(aspect_reclass, crs=crs(climate))
slope_proj <- projectRaster(slope_reclass, crs=crs(climate))
```

```{r}
#Crop
climate_crop <- crop(climate, soils_proj)
DEM_crop <- crop(DEM_proj, soils_proj)
aspect_crop <- crop(aspect_proj, soils_proj)
slope_crop <- crop(slope_proj, soils_proj)

climate_resample <- resample(climate_crop,DEM_crop,method='ngb',progress='text')
soils_resample <- resample(soils_proj,DEM_crop,method='ngb',progress='text')
aspect_resample <- resample(aspect_crop,DEM_crop,method='ngb',progress='text')
slope_resample <- resample(slope_crop,DEM_crop,method='ngb',progress='text')

predictors <- stack(climate_resample, soils_resample, DEM_crop, aspect_resample, slope_resample)
```

