---
title: "Bradypus"
author: "Brad Anderson"
date: "October 10, 2018"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(dismo)
library(tidyverse)
library(sf)
library(sp)
library(rgdal)
library(maptools)


```

#Set Data Locations
```{r PARAMETERS and FILE LOCATIONS, include=FALSE}

#Climate Variables Folder
variable_path <- file.path("H:/SDM/Climate/CCMSM4_rcp85/2010-2039/")

#Soil
soils <- raster("H:/MaxEnt/Environmental Variables/SSURGO Soil/sb_soil.tif")

#DEM
DEM <- raster("H:/MaxEnt/Environmental Variables/Elevation Slope Aspect/DEM.tif")

#Aspect
aspect <- raster("H:/MaxEnt/Environmental Variables/Elevation Slope Aspect/Aspect.tif")

#Slope
slope <- raster("H:/MaxEnt/Environmental Variables/Elevation Slope Aspect/Slope.tif")

#Extent (I am using two USFS Seed Zones)
extent <- read_sf("H:/MaxEnt/Extent",
                      layer="boundary")


```

#Import environmental data:
```{r RasterStack & Define Projection}
#Call all .tif files from the storage location
variables <- list.files(variable_path, pattern='tif$', full.names=TRUE )

#Stack climate tif files into a RasterStack
climate <- stack(variables)

#Define project (For some reason the BCM data comes unprojected)
crs(climate) <- CRS('+init=epsg:3310')



```

#Prepare Data
```{r Data Prep}
#Crop
climate_crop <- crop(climate, extent)
DEM_crop <- crop(DEM, extent)
aspect_crop <- crop(aspect, extent)
slope_crop <- crop(slope, extent)
soils_crop <- crop(soils, extent)

#Re-assign numbers
#soils_reclass <- reclassify(soils_crop,rcl=c(120,150,NA))
aspect_reclass <- reclassify(aspect_crop,rcl=c(-Inf,0,NA))
#slope_reclass <- reclassify(slope_crop,rcl=c(-Inf,0,NA))

#Reproject to NAD83 CA Teale Albers (Too big to run? I am getting an error...)
soils_proj <- projectRaster(soils_crop, crs=crs(climate))
DEM_proj <- projectRaster(DEM_crop, crs=crs(climate))
aspect_proj <- projectRaster(aspect_reclass, crs=crs(climate))
slope_proj <- projectRaster(slope_crop, crs=crs(climate))


```

```{r}

climate_resample <- resample(climate_crop,DEM_proj,method='ngb',progress='text')
soils_resample <- resample(soils_proj,DEM_proj,method='ngb',progress='text')
aspect_resample <- resample(aspect_proj,DEM_proj,method='ngb',progress='text')
slope_resample <- resample(slope_proj,DEM_proj,method='ngb',progress='text')

predictors <- stack(climate_resample, soils_resample, DEM_proj, aspect_resample, slope_resample)


```

```{r Convert Cliamte to Ascii for MaxEnt, include=FALSE}

#unstack to list
x <- unstack(climate_resample)

file.dir <- "H:/MaxEnt/Test/"
climate.variable.names <- c("aet","aprpck","cwd","pet","ppt","rch","run","tmn","tmx")

for(i in 1:length(x)) {
  
  fn <- paste0(file.dir,climate.variable.names[i],".asc")
  writeRaster(x[[i]],fn,format="ascii",overwrite=T)
  
}


```

```{r Convert other layers to ASCII}

```


